### PR TITLE
Class loader for signed jars

### PR DESCRIPTION
**Pull request by stanbar**
ModuleClassLoader can now load signed jars  #44 
add keystore and certificate

Took 2 hours 57 minutes

### CODE REVIEW

**Comment by PatrykMilewski** [comment]
it's hard to review these changes, because it contains #48 and it was already marged

**Comment by stanbar** [comment]
I will try to merge with master, so hopefully the number of changes should reduce

**Comment by PatrykMilewski** [comment]
okay, then I'm waiting

**Comment by stanbar** [comment]
It didn't help. So here is what this PR really do:
Generating java byte array initialization from Certificate file, for embedding certificate into bytecode.
https://github.com/RaspberryWallet/Backend/pull/49/files?utf8=%E2%9C%93&diff=split#diff-876b9f5f6b87bf29a445cf11c60958eb 

update README on how to sign modules
https://github.com/RaspberryWallet/Backend/pull/49/files?utf8=%E2%9C%93&diff=split#diff-04c6e90faac2675aa89e2176d2eec7d8

Add PKI impl, it does: lazy init on x509 cert, perform self integrity check, and hold certificate as a byte array.
https://github.com/RaspberryWallet/Backend/pull/49/files?utf8=%E2%9C%93&diff=split#diff-6b411bc7c5c3d8191799f5994a92a207

Add JarVerifier to verify if the jar that we are importing is signed by our certificate.
It can also check if the program itself is signed by the certificate.
https://github.com/RaspberryWallet/Backend/pull/49/files?utf8=%E2%9C%93&diff=split#diff-de0a9581187a92051e52602850147629

**Comment by PatrykMilewski** [comment]
This closes #44

**Pull request merged**
