### PR TITLE
ktor replace Netty with Jetty

### PR DESCRIPTION
**Pull request by stanbar**
Let's test if Jetty is better than Netty in our case
Took 7 minutes

### CODE REVIEW

**Comment by PatrykMilewski** [comment]
One question, why there is PR if you dont want to merge it? XD @stasbar

**Comment by stanbar** [comment]
it's signal for you to not merge it, until @furlel test it and it really perform better than Netty

**Comment by PatrykMilewski** [comment]
@stasbar okay, but imo it should be added as issue

**Comment by stanbar** [comment]
But I wanted to set the environment for Jetty, so @Furfel would just simply checkout and test it

**Comment by stanbar** [comment]
@Furfel did you test it ?

**Comment by pfoof** [comment]
Ok, going to test it

**Comment by stanbar** [comment]
Jetty doesn't change anything. Problem was in `SecureRandom` = `dev/urandom`

**Pull request closed without merging**
