### PR TITLE
Module refactoring

### LINKED ISSUE #107: Abstract Module class is too complicated
I'm writting README about how modules works and I found, that if you look into a code of a Module class:
https://github.com/RaspberryWallet/Backend/blob/master/Manager/src/main/java/io/raspberrywallet/manager/modules/Module.java

Then you notice, it's really compilcated and long. It's kinda problem, due to users getting demotivated to implement their custom modules. I belive, that user should see just abstract methods, that MUST be implemented, for module to work with our wallet. Also I think, that Module class should be splitted to 2 classes.

My proposal of solution, waiting for yours, because I don't really like it:
- ParentModule class: contains all the abstract methods, all protected methods and default logic for all of them
- Module class: extends after ParentModule, contains again abstract methods but just them, nothing more

Or maybe something with interfaces?

### PR DESCRIPTION
**Pull request by stanbar**
added missing JavaDocs
added `IModule` abstraction layer to `Module` class
refactoring
closes #107 

Took 52 minutes

### CODE REVIEW

**Review by PatrykMilewski — CHANGES_REQUESTED** [review]
Could you add inheritance in JavaDocs?
https://dzone.com/articles/inheriting-javadoc-method-comments

It would make Module cleaner

**Comment by stanbar** [comment]
Like this ?

**Comment by PatrykMilewski** [comment]
@stasbar yup, do you think it's better? it would force users to look more on interface than abstract class, I think, that it's good approach

**Review by PatrykMilewski — APPROVED** [review]

**Comment by stanbar** [comment]
Well, I think that is doesn't change a lot, because user doesn't even see the `IModule`. If you want to create module you still need to extend `Module<T>`, and work with it. `IModule` is used only internally.

**Comment by PatrykMilewski** [comment]
You are right, let's go back to previous version, sorry for trouble

**Comment by stanbar** [comment]
No problem it was good exercise. Anyway let's merge this PR, since there are more refactoring done.

**Pull request merged**
