### PR TITLE
Added input from user functions.

### PR DESCRIPTION
**Pull request by thefurfel**
Added user input functions (such as passing PIN from frontend).

### CODE REVIEW

**Comment by stanbar** [comment]
How Manager can know what key should be used to assign input to ?
There should be some standardized two-way protocol between module-manager [-frontend optionally]

**Comment by thefurfel** [comment]
```
<div id="module-form">
<!-- loading PIN_module.tpl -->
<form action="/ajaxSubmitForm" method="post">
    <input type="hidden" name="className" value="io.raspberrywallet.modules.PINModule" />
    <input type="text" name="pin" />
    <input type="text" name="pin2" /> 
    <button onclick="Module.add(1)">1</button>
    <button onclick="Module.add(2)">2</button>
    <button onclick="Module.submitForm()">Ok</button>
</form>
<!-- end PIN_module.tpl -->
</div>
```

Module.java
`var_dump(input) = HashMap<String, String>() = { "pin"=>"1234", "pin2"=>"4567" }`

**Comment by stanbar** [comment]
Ok, looks interesting.
Manager interface require tweaks then. 
This will be required in odered to embeed HTML code inside React:
https://stackoverflow.com/a/19277723/4233693

**Review by stanbar — APPROVED** [review]
Looks good

**Pull request merged**
